Updates to run-all

diff --git a/stig/run-all b/stig/run-all
--- a/stig/run-all
+++ b/stig/run-all
@@ -4,42 +4,28 @@ BASEDIR="$(dirname "${SCRIPT}")"
 SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
+. /.functions
 
 run()
 {
-	say "🚀 Running: ${@}"
+	running "Running: ${@}"
 	( exec "${@}" )
 	return ${?}
 }
 
-ok()
-{
-	say "✅ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit 1
-}
-
-say "👀 Running the STIG remediation scripts"
+eyes "Running the STIG remediation scripts"
 while read S ; do
-	run "${S}" && ok "Remediation successful!" || fail "Remediation failed"
+	DN="$(dirname "${S}")"
+	BN="$(basename "${S}")"
+	MARKER="${DN}/.${BN}.applied"
+
+	# Avoid double-application of STIG fixups
+	[ -e "${MARKER}" ] && continue
+
+	running "Applying [${BN}]..."
+	OUT="$(run "${S}" 2>&1)" && ok "Remediation successful!" || fail "Remediation failed (rc=${?}):\n${OUT}"
+
+	echo -e "Remediated on $(date -Ins -u)\n\n${OUT}" > "${MARKER}" || fail "Failed to create the STIG remediation marker"
+
 done < <(find "${BASEDIR}" -type f -name "*.sh" -executable | sort)
 ok "Remediations complete!"
