Fix apply-fixes to the new way of applying CVEs
[skip ci] don't build

diff --git a/apply-fixes b/apply-fixes
--- a/apply-fixes
+++ b/apply-fixes
@@ -8,19 +8,16 @@ set_or_default FIXES_DIR "/fixes"
 [ ${#} -gt 0 ] || set -- "${FIXES_DIR}"
 
 for DIR in "${@}" ; do
-	require_dir_readwrite "${DIR}"
+	require_dir_readable "${DIR}"
 
 	doing "Applying fixes from [${DIR}] ..."
 
 	COUNT=0
 	while read FIX ; do
-		doing "Applying ${FIX} ..."
-		"${FIX}" || fail "Failed to apply the fix from ${FIX} (rc=${?})"
+		running "Applying ${FIX} ..."
+		OUT="$( "${FIX}" 2>&1 )" || fail "Failed to apply the fix from ${FIX} (rc=${?}):\n${OUT}"
+		ok "Fix applied!"
 		(( ++COUNT ))
-		rm -f "${FIX}" &>/dev/null || true
 	done < <(find "${DIR}" -mindepth 1 -maxdepth 1 -type f -not -name '.*' -not -name '*.disabled' -executable)
-
-	rm -rf "${DIR}" || warn "Failed to remove the fixes directory at [${DIR}]"
-
 	ok "${COUNT} fixes applied from [${DIR}]!"
 done
