Updated to deploy a single artifact
This will be more useful for each container to self-deploy whatever artifacts it requires, in whatever ways it sees fit. The single, prescribed mechanism from before doesn't really work well for us.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -3,8 +3,6 @@ set -euo pipefail
 
 [ -v BASE_DIR ] || BASE_DIR="/app"
 [ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
-[ -v FILE_DIR ] || FILE_DIR="${INIT_DIR}/deploy-src"
-[ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"
 [ -v FORCE_HASHES ] || FORCE_HASHES="false"
 [ -v DEPL_URL ] || DEPL_URL="http://app-deploy"
 
@@ -12,13 +10,6 @@ case "${FORCE_HASHES,,}" in
 	true | t | yes | y | 1 | enabled | enable | en | on ) FORCE_HASHES="true" ;;
 	* ) FORCE_HASHES="false" ;;
 esac
-
-cleanup() {
-	# Try to delete the downloaded stuff
-	if [ -v FILE_DIR ] && [ -d "${FILE_DIR}" ] ; then
-		rm -rf "${FILE_DIR}" &>/dev/null || true
-	fi
-}
 
 # Make sure we run cleanup on exit
 trap cleanup EXIT
@@ -32,179 +23,133 @@ fail() {
 	exit ${EXIT_CODE:-1}
 }
 
-list_files() {
-	local DIR="."
-	[ ${#} -gt 0 ] && DIR="${1}"
-	DIR="$(readlink -f "${DIR}")"
-	if [ -d "${DIR}" ] ; then
-		find "${DIR}" -mindepth 1 -maxdepth 1 | sort | sed -e "s:^${DIR}/::g"
-	else
-		echo "${DIR}"
-	fi
+cleanup() {
+	[ -v TARGET_TMP_DIR ] && [ -n "${TARGET_TMP_DIR}" ] && [ -d "${TARGET_TMP_DIR}" ] && rm -rf "${TARGET_TMP_DIR}" &>/dev/null
 }
 
-deploy_zip() {
-	local SRC="${1}"
-	local TGT="${2}"
-	local BN=""
-	[ ${#} -ge 3 ] && BN="${3}"
-
-	if [ ! -s "${SRC}" ] ; then
-		say "There is no source file [${SRC}], or it's empty"
-		return 1
-	fi
-	local SRC_NAME="${SRC##*/}"
-
-	local SUM=""
-	if ! ${FORCE_HASHES} ; then
-		[ -s "${SRC}.sum" ] && SUM="$(<"${SRC}.sum")"
-	fi
-
-	local NEW_VER="${VER}"
-	[ -s "${SRC}.ver" ] && NEW_VER="$(<"${SRC}.ver")"
-
-	if [[ ! "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
-		${FORCE_HASHES} || say "Failed to find the cached checksum for [${SRC}], or its contents are invalid. Computing it directly..."
-		read SUM REST < <(sha256sum "${SRC}")
-		if [[ ! "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
-			say "Failed to compute the sha256 checksum for [${SRC}]"
-			return 1
-		fi
-	fi
-
-	local MARK="${TGT}/.version"
-	if [ -e "${MARK}" ] ; then
-		local OLD_DATE=""
-		local OLD_NAME=""
-		local OLD_VER=""
-		local OLD_SUM="<none>"
-		local EXISTING_LOADED="false"
-
-		if [ -e "${MARK}" ] ; then
-			# We explicitly don't call sort b/c we want to get the last record on the list,
-			# regardless of its contents
-			local REST=""
-			IFS="/" read OLD_DATE OLD_NAME OLD_VER OLD_SUM REST < <(grep -v '^[[:space:]]*#' "${MARK}" | grep -v '^[[:space:]]*$' | egrep "/${SRC_NAME}/" | tail -1)
-			[ -n "${OLD_SUM}" ] && EXISTING_LOADED="true"
-		fi
-
-		if "${EXISTING_LOADED}" ; then
-			if [ "${SUM}" == "${OLD_SUM}" ] ; then
-				say "The file [${SRC_NAME}] appears to already be deployed into [${TGT}] since ${OLD_DATE} (version = ${OLD_VER}, verified by checksum)."
-				return 0
-			fi
-			say "File content change detected for [${SRC_NAME}] through file checksum:\n\tEXISTING: [${OLD_VER} = ${OLD_SUM}]\n\tINCOMING: [${NEW_VER} = ${SUM}]"
-		else
-			say "Couldn't find a prior installation record for [${SRC_NAME}], deploying the file:\n\tINCOMING: [${NEW_VER} = ${SUM}]"
-		fi
-	else
-		say "Version tracking hasn't yet begun for ${TGT} (the marker file [${MARK}] is missing)"
-	fi
-
-	local DEST="${TGT}"
-	if [ -n "${BN}" ] ; then
-		DEST+="/${BN}"
-		mkdir -p "${DEST}" || fail "Failed to create the deployment subdirectory for [${SRC}] at [${DEST}]"
-	fi
-
-	if [[ "${SRC}" =~ ^(.*/)?[Cc][Oo][Pp][Yy][.]([^/]+)$ ]] ; then
-		# If the file is meant to be a copy (i.e. the filename starts with "copy.",
-		# case-insensitive) then we just copy it into the destination with its
-		# original basename, minus the "copy." prefix.
-		cp -vf "${SRC}" "${DEST}/${BASH_REMATCH[2]}"
-	else
-		# If the file is not meant to be a copy, then we extract its contents into the
-		# destination, clobbering any existing files.
-		unzip -o -d "${DEST}" "${SRC}"
-	fi
-
-	# Add the marker record for this version
-	echo -e "$(date -u -Ins)/${SRC_NAME}/${NEW_VER}/${SUM}" >> "${MARK}"
+usage() {
+	{
+		echo -e "usage: ${BASH_SOURCE:-${0}} operation artifact targetDir"
+		echo -e ""
+		echo -e "    operation  => copy, extract, or extractdir"
+		echo -e "    artifact   => path of the artifact to deploy (from DEPL_URL)"
+		echo -e "    targetDir  => the directory into which to deploy"
+		echo -e ""
+		echo -e "    Operations:"
+		echo -e "        copy       : copy the file verbatim into targetDir"
+		echo -e "        extract    : unzip the file into targetDir (unzip -o -d ...)"
+		echo -e "        extractDir : like extract, but create a subdirectory with"
+		echo -e "                     the basename of the file, minus the extension"
+	} 1>&2
+	exit 1
 }
 
-deploy_war() {
-	[[ "${1}" =~ ^(.+)[.][wW][aA][rR]$ ]] || fail "The given filename [${1}] is not a valid WAR file name"
-	local BASENAME="${BASH_REMATCH[1]}"
-	BASENAME="${BASENAME##*/}"
-	deploy_zip "${1}" "${2}" "${BASENAME}"
-}
+[ ${#} -eq 3 ] || usage
 
-[ -v VER ] || VER="(unknown)"
-[ -n "${VER}" ] || VER="(unknown)"
+OPERATION="${1,,}"
+case "${OPERATION,,}" in
+	copy | extract | extractdir | extract-dir ) OPERATION="${OPERATION,,}" ;;
+	* ) fail "Invalid operation [${OPERATION}]" ;;
+esac
 
-#
-# Clone the directories from the deployment
-#
-[ -d "${FILE_DIR}" ] || mkdir -p "${FILE_DIR}"
-say "Downloading the list of available directories"
-wget --no-verbose --spider -r --no-parent --no-host-directories -P "${FILE_DIR}" "${DEPL_URL}"
-say "\tList downloaded"
+ARTIFACT="${2}"
 
-while read DIR ; do
-	TGT="${DEPL_DIR}/${DIR##*/}"
+[[ "${ARTIFACT}" =~ [^/]$ ]] || fail "The artifact name may not end in a slash: [${ARTIFACT}]"
 
-	#
-	# Deploy ZIP files ... this is straightforward
-	#
-	if [ ! -d "${TGT}" ] ; then
-		say "There is no destination directory [${TGT}], will skip deploying files meant for it"
-		continue
+# Sanitize the artifact name (single slashes, remove leading slash)
+ARTIFACT="$(echo -n "${ARTIFACT}" | sed -e 's;/+;/;g' -e 's;^/;;g')"
+ARTIFACT_NAME="${ARTIFACT##*/}"
+
+TARGET_DIR="${3}"
+[ -e "${TARGET_DIR}" ] || fail "The target directory [${TARGET_DIR}] does not exist"
+[ -d "${TARGET_DIR}" ] || fail "The target path [${TARGET_DIR}] is not a directory"
+[ -r "${TARGET_DIR}" ] || fail "The target path [${TARGET_DIR}] is not readable"
+[ -w "${TARGET_DIR}" ] || fail "The target path [${TARGET_DIR}] is not writable"
+[ -x "${TARGET_DIR}" ] || fail "The target path [${TARGET_DIR}] is not executable"
+TARGET_DIR="$(readlink -f "${TARGET_DIR}")"
+
+TARGET_TMP_DIR="${TARGET_DIR}/.deploy.$(uuidgen)"
+mkdir -p "${TARGET_TMP_DIR}" || fail "Failed to create the temporary work directory"
+TARGET_TMP_FILE="${TARGET_TMP_DIR}/${ARTIFACT_NAME}"
+
+# Check for artifact availability
+SOURCE_URL="${DEPL_URL}/${ARTIFACT}"
+HTTP_CODE="$(curl -kL -s --head -o /dev/null -w "%{http_code}" "${SOURCE_URL}")"
+[ ${HTTP_CODE} -lt 400 ] || fail "The artifact [${ARTIFACT}] is not available for deployment (HTTP CODE = ${HTTP_CODE})"
+
+# The artifact is there, so pull it into the destination
+curl -kL --fail -s -o "${TARGET_TMP_FILE}" "${SOURCE_URL}"
+
+# Same with the version and the checksum, but it's OK if these aren't there b/c
+# we can come up with defaults
+
+NEW_VER="$(curl -kL -s --fail "${DEPL_URL}/${ARTIFACT}.ver" 2>/dev/null || true)"
+[ -n "${NEW_VER}" ] || NEW_VER="(unknown)"
+
+# By default, no checksum...
+SUM=""
+
+# If we're not forcing a local hash computation, we try to download the cached value
+${FORCE_HASHES} || SUM="$(curl -kL -s --fail "${DEPL_URL}/${ARTIFACT}.sum" 2>/dev/null || true)"
+
+# If the sum is invalid, or we're requesting local checksum computation, we do just that
+if [[ ! "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
+	${FORCE_HASHES} || say "Failed to find the cached checksum for [${ARTIFACT}], or its contents are invalid. Computing it directly..."
+	read SUM REST < <(sha256sum "${TARGET_TMP_FILE}")
+	[[ "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] || fail "Failed to compute the sha256 checksum for [${ARTIFACT}]"
+fi
+SUM="${SUM,,}"
+
+# This is the file track marker where we'll track the deployment status
+MARKER_FILE="${TARGET_DIR}/.version"
+if [ -e "${MARKER_FILE}" ] ; then
+	OLD_DATE=""
+	OLD_ARTIFACT=""
+	OLD_VER=""
+	OLD_SUM="<none>"
+	EXISTING_LOADED="false"
+
+	if [ -e "${MARKER_FILE}" ] ; then
+		# We explicitly don't call sort b/c we want to get the last record on the list,
+		# regardless of its contents
+		REST=""
+		IFS="|" read OLD_DATE OLD_VER OLD_SUM OLD_ARTIFACT < <(sed -e '/^\s*#.*$/d' -e '/^\s*$/d' < "${MARKER_FILE}" | egrep "\|[0-9a-fA-F]{64}\|${ARTIFACT}$" | tail -1)
+		[ -n "${OLD_SUM}" ] && EXISTING_LOADED="true"
 	fi
 
-	# Ok ... now the fun part: download the files from the directory we're looking at
-	say "Downloading the files for [${DIR##*/}]..."
-	wget --no-verbose --mirror --no-parent -nH -P "${FILE_DIR}" "${DEPL_URL}/${DIR##*/}/"
-	say "\tFiles downloaded"
-
-	# Canonicalize the target root directory
-	TGT="$(readlink -f "${TGT}")"
-
-	# The directory is there ... find any files meant for it,
-	# and install them in alphanumeric order
-
-    # First the WARs, to afford the ZIPs an opportunity to override crap
-	#
-	# Deploy WAR files - they each go into a subdirectory that shares their basename, minus the
-	# WAR extension (case-insensitive) ... i.e. arkcase.war gets its contents dumped straight
-    # into ${TGT}/arkcase
-	#
-	while read FILE ; do
-		say "Deploying the WAR file [${FILE}] into [${TGT}]..."
-		deploy_war "$(readlink -f "${FILE}")" "${TGT}" || fail "Failed to deploy the WAR file [${FILE}] into [${TGT}]"
-	done < <(find "${DIR}" -mindepth 1 -maxdepth 1 -type f -iname '*.war' | sort)
-
-    # Second the ZIPs, in case they want to clobber anything the WARs put out
-	#
-	# Deploy ZIP files - they go straight into the subdirectory itself, no massaging, no special
-	# considerations... straight up "dump the contents into ${TGT}"
-	while read FILE ; do
-		say "Deploying the ZIP file [${FILE}] into [${TGT}]..."
-		deploy_zip "$(readlink -f "${FILE}")" "${TGT}" || fail "Failed to deploy the ZIP file [${FILE}] into [${TGT}]"
-	done < <(find "${DIR}" -mindepth 1 -maxdepth 1 -type f -iname '*.zip' | sort)
-done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type d | sort)
-
-#
-# This is the only fix we know must be applied FOR SURE each time
-#
-realm-fix
-
-#
-# Apply customizations and reconfigurations
-#
-if [ ! -d "${INIT_DIR}" ] ; then
-	say "No initialization to perform, exiting"
-	exit 0
+	if "${EXISTING_LOADED}" ; then
+		if [ "${SUM,,}" == "${OLD_SUM,,}" ] ; then
+			say "The artifact [${ARTIFACT}] appears to already be deployed into [${TARGET_DIR}] since ${OLD_DATE} (version = ${OLD_VER}, verified by checksum)."
+			exit 0
+		fi
+		say "File content change detected for [${ARTIFACT}] through file checksum:\n\tEXISTING: [${OLD_VER} = ${OLD_SUM}]\n\tINCOMING: [${NEW_VER} = ${SUM}]"
+	else
+		say "Couldn't find a prior installation record for [${ARTIFACT}], deploying the file:\n\tINCOMING: [${NEW_VER} = ${SUM}]"
+	fi
+else
+	say "Version tracking hasn't yet begun for ${TARGET_DIR} (the marker file [${MARKER_FILE}] is missing)"
 fi
 
-cd "${INIT_DIR}"
-while read f ; do
-	[ -s "${f}" ] || continue
-	[ -r "${f}" ] || continue
-	[ -x "${f}" ] || continue
+case "${OPERATION,,}" in
+	extract )
+		unzip -o -d "${TARGET_DIR}" "${TARGET_TMP_FILE}"
+		;;
 
-	say "Executing initialization script [${f}]..."
-	( "${f}" ) || fail "\tInitialization script [${f}] failed (rc=${?})"
-done < <(list_files)
+	extractdir | extract-dir )
+		BASENAME="${ARTIFACT_NAME%.*}"
+		mkdir -p "${TARGET_DIR}/${BASENAME}"
+		unzip -o -d "${TARGET_DIR}/${BASENAME}" "${TARGET_TMP_FILE}"
+		;;
 
-say "Configuration Initialization Complete"
+	copy )
+		mv -vf "${TARGET_TMP_FILE}" "${TARGET_DIR}/${ARTIFACT_NAME}"
+		;;
+
+	* )
+		fail "Unrecognized operation requested: [${OPERATION}]"
+		;;
+esac
+
+# Add the marker record for this version
+echo -e "$(date -u -Ins)|${NEW_VER}|${SUM,,}|${ARTIFACT}" >> "${MARKER_FILE}"
 exit 0
