Add is_valid_envvar to properly check envvar names
[skip ci] don't build

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -737,6 +737,19 @@ to_array()
 	return 0
 }
 
+#
+# usage: is_valid_envvar VAR_NAME
+#
+# Returns 0 if the given variable name is valid for
+# an environment variable, non-0 otherwise
+#
+is_valid_envvar()
+{
+	local __VAR="${1}"
+	[[ "${__VAR}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || return 1
+	return 0
+}
+
 __var_set_tool()
 {
 	[ ${#} -ge 2 ] || return 1
@@ -745,7 +758,7 @@ __var_set_tool()
 
 	local __VAR="${1}"
 
-	[[ "${__VAR}" =~ ^[a-zA-Z0-9_]+$ ]] || fail "Invalid variable name [${__VAR}]"
+	is_valid_envvar "${__VAR}" || fail "Invalid variable name [${__VAR}]"
 
 	local __X=""
 	local __RESULT=""
@@ -1438,7 +1451,7 @@ execute_unless()
 	local __VAR="${1}"
 	shift
 
-	[[ "${__VAR}" =~ ^[a-zA-Z0-9_]+$ ]] || fail "Invalid variable name [${__VAR}]"
+	is_valid_envvar "${__VAR}" || fail "Invalid variable name [${__VAR}]"
 
 	#
 	# Show the command about to be executed
