Add support for specifying the key variable to use

diff --git a/scripts/decrypt b/scripts/decrypt
--- a/scripts/decrypt
+++ b/scripts/decrypt
@@ -6,12 +6,20 @@ set -euo pipefail
 set_as_boolean DEBUG
 ${DEBUG} && set -x
 
-set_or_default CURL_ENCRYPTION_KEY
-if [ -n "${CURL_ENCRYPTION_KEY}" ] ; then
+KEY_VAR="CURL_ENCRYPTION_KEY"
+if [ ${#} -ge 1 ] ; then
+	export V="${1}"
+	( echo "${!V}" ) &>/dev/null || fail "Invalid variable name [${V}]" 1>&2
+	unset V
+	KEY_VAR="${1}"
+fi
+
+set_or_default "${KEY_VAR}"
+if [ -n "${!KEY_VAR}" ] ; then
 	# Decrypt the value
 	exec openssl aes-256-cbc \
 		-a -A -salt -iter 5 -d \
-		-kfile <(echo -n "${CURL_ENCRYPTION_KEY}") 2>/dev/null
+		-kfile <(echo -n "${!KEY_VAR}") 2>/dev/null
 else
 	# Don't decrypt anything ...
 	exec cat
