Use ENCRYPTION_KEY vs. CURL_ENCRYPTION_KEY

diff --git a/scripts/decrypt b/scripts/decrypt
--- a/scripts/decrypt
+++ b/scripts/decrypt
@@ -6,12 +6,10 @@ set -euo pipefail
 set_as_boolean DEBUG
 ${DEBUG} && set -x
 
-KEY_VAR="CURL_ENCRYPTION_KEY"
+KEY_VAR="ENCRYPTION_KEY"
 if [ ${#} -ge 1 ] ; then
-	export V="${1}"
-	( echo "${!V}" ) &>/dev/null || fail "Invalid variable name [${V}]" 1>&2
-	unset V
 	KEY_VAR="${1}"
+	is_valid_envvar "${KEY_VAR}" || fail "Invalid variable name [${KEY_VAR}]" 1>&2
 fi
 
 set_or_default "${KEY_VAR}"
