Add support for secrets for Docker build

diff --git a/scripts/mvn-get b/scripts/mvn-get
--- a/scripts/mvn-get
+++ b/scripts/mvn-get
@@ -7,6 +7,8 @@ DEFAULT_MVN_CENTRAL_REPO="https://repo1.maven.org/maven2"
 set_or_default DOWNLOAD_RETRY 30
 set_or_default DOWNLOAD_RETRY_SEC 5
 
+set_or_default MVN_AUTH_SECRET "/run/secrets/mvn_auth"
+
 download()
 {
 	local URL="${1}"
@@ -128,6 +130,8 @@ if [ -v MVN_GET_SERVER_ID ] ; then
 	MVN_GET_PASSWORD="$(mvn-crypt --quiet server decrypt "${MVN_GET_SERVER_ID}" password)"
 	[ -n "${MVN_GET_PASSWORD}" ] || fail "The password for server [${MVN_GET_SERVER_ID}] is empty or nonexistent"
 	NEED_DECRYPT="false"
+elif is_file_readable "${MVN_AUTH_SECRET}" ; then
+	source "${MVN_AUTH_SECRET}" || fail "Failed to source the authentication secret at [${MVN_AUTH_SECRET}]"
 fi
 
 AUTH=""
